name: HostApp
options:
  bundleIdPrefix: com.jumpdesktop
targets:
  HostApp:
    type: application
    platform: macOS
    deploymentTarget: "12.3"
    sources:
      - Sources
    dependencies:
      - package: WebRTC
        product: WebRTC
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jumpdesktop.HostApp
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_STYLE: "Automatic"
        DEVELOPMENT_TEAM: ""
        ENABLE_HARDENED_RUNTIME: NO
        CODE_SIGN_ENTITLEMENTS: HostApp.entitlements
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: $(SRCROOT)/Info.plist
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "WebRTC 오디오 스트리밍 송출을 위해 시스템 및 마이크 사운드 입력 권한이 필요합니다."
        INFOPLIST_KEY_NSCameraUsageDescription: "WebRTC 비디오 스트리밍 송출을 위해 카메라 권한이 필요합니다."

packages:
  WebRTC:
    url: https://github.com/stasel/WebRTC.git
    from: 104.0.0
